name: update
on:
  schedule:
    - cron: '30 19 * * *' #每日更新
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest #运行
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: 安装node环境
        uses: actions/setup-node@master
        with:
          node-version: "12.x"
      - name: 'Git set'
        run: |
             git init
             git pull
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
           python-version: 3.7 #v3
      - name: 'Install requirements'
        run: |
             pip install wget
             pip install bs4
             pip install urllib3 #安装依赖
             pip install retrying
      - name: 'Working'
        run: 
          python update.py #运行主程序
      - name: Record time  
        run: echo `date` > date.log

      - name: Commit files
        run: |
          git diff
          git config --local user.email "w00989988@gmail.com"
          git config --local user.name "Haoqi7"
          git add -A
          git commit -m "`date '+%Y-%m-%d %H:%M:%S'`" || exit #动态提交信息
          git status
          git push -f
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB }}
  sesrch:
    needs: build
    runs-on: ubuntu-latest #运行环境
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: 'Git set'
        run: |
             git init
             git pull
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
           python-version: 3.7 #v3
      - name: 'Install requirements'
        run: |
             pip install bs4
      - name: 'Working'
        run: 
          python search.py #运行主程序
      - name: Commit files
        continue-on-error: True
        run: |
          git diff
          git config --local user.email "w00989988@gmail.com"
          git config --local user.name "Haoqi7"
          git add -A
          git commit -m "[RPageSearch]`date '+%Y-%m-%d %H:%M:%S'`" || exit #动态提交信息
          git status
          git push -f
